name: Golang CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
  - cron: '15 3 * * 0'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Setup tools
      run: |
        go get golang.org/x/lint/golint
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Project
      run: ./buildutil

  docker_build:
    runs-on: ubuntu-20.04
    name: Docker Build
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'rebuy-de/cost-exporter' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate image tags
      shell: bash
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
          echo "##[set-output name=tags;]quay.io/rebuy/cost-exporter:${GITHUB_HEAD_REF}"
        else
          echo "##[set-output name=tags;]quay.io/rebuy/cost-exporter:main,\
            quay.io/rebuy/cost-exporter:latest"
        fi
      id: generate_tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.generate_tags.outputs.tags }}
