name: Publish release artifacts

on:
  release:
    types: [created]

jobs:
  release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Project binaries
      run: ./buildutil -x linux/amd64 -x linux/arm64
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/cost*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
